Better graphics
arikhativa/transcendence pull request #110
Opened 2024-01-27 17:10 UTC by dVaGaymer

2024-01-27 17:28 UTC, arikhativa requested changes
some small changes and add to trello

2024-01-27 17:28 UTC, arikhativa commented on django/src/game/static/Ball.js
> +        // ctx.fillRect(this.x - this.w/2, this.y - this.h/2, this.w, this.h);
remove

2024-01-27 17:28 UTC, arikhativa commented on django/src/game/static/Player.js
> +        // ctx.fillRect(this.x - this.w / 2, this.y - this.h_visual / 2, this.w, this.h_visual);
remove

2024-01-28 10:08 UTC, llanahp approved these changes

2024-01-28 12:30 UTC, arikhativa approved these changes

2024-01-28 12:32 UTC, merged